"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import warnings
from pathlib import Path

from django.utils.translation import gettext_lazy as _

from .database import *

# Import module-specific configurations
from .accounts import *

from .logging_config import configure_logging

# Suppress specific warnings
warnings.filterwarnings('ignore', category=SyntaxWarning, module='flanker')
warnings.filterwarnings('ignore', message='.*invalid escape sequence.*')

# ============================
# General Settings
# ============================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

_extra_plugin_roots = [
    value.strip()
    for value in os.getenv("LENS_PLUGIN_ROOTS", "").split(",")
    if value.strip()
]
_default_plugin_root = str(BASE_DIR.parent.parent / "plugins")
LENS_PLUGIN_ROOTS = list(dict.fromkeys([
    _default_plugin_root,
    *_extra_plugin_roots,
]))

# Environment variables are loaded via docker-compose env_file configuration
# All settings use os.getenv() to read from environment variables

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    'django-insecure-$k0f0!qp@0k%1xa_)zy!+xvwpv)+&$q&!d69ma@l615bdc2ytd')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:8000,http://127.0.0.1:8000'
).split(",")

# Trust proxy headers from nginx
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ============================
# Logging Configuration
# ============================

LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'info').upper()
configure_logging(LOG_LEVEL)

# ============================
# Application Definitions
# ============================

# Django & thrid party apps
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Required by django-allauth for managing site-specific data,
    # such as site domains and configurations.
    'django.contrib.sites',

    # Core Django Rest Framework (DRF) package that provides tools
    # to build APIs and handle request/response data in various formats
    # (JSON, XML, etc.).
    'rest_framework',

    # Enables token-based authentication in DRF, allowing users
    # to authenticate using tokens.
    'rest_framework.authtoken',

    # A Django app that integrates dj-rest-auth with Django-allauth,
    # providing authentication and registration endpoints for RESTful APIs.
    'dj_rest_auth',

    # Provides JWT authentication support for Django REST Framework,
    # allowing for secure token-based authentication using JSON Web Tokens.
    'rest_framework_simplejwt',

    # Django-allauth package, which provides comprehensive user authentication,
    # registration, and account management.
    'allauth',

    # A submodule of django-allauth that handles user account registration,
    # login, password management, and more.
    'allauth.account',

    # Extends allauth to support social authentication
    # (e.g., logging in with Facebook, Google, etc.).
    'allauth.socialaccount',

    # Social account providers
    'allauth.socialaccount.providers.google',

    # Headless API for frontend-backend separation (allauth >= 65.0.0)
    # Provides REST API endpoints for authentication without Django forms
    'allauth.headless',

    # Adds user registration endpoints to dj-rest-auth, enabling
    # JWT-based user registration and management
    # (e.g., email verification, password reset).
    'dj_rest_auth.registration',

    # Provides tools for generating interactive API documentation
    # with Swagger UI or ReDoc, making it easier to visualize and
    # test API endpoints.
    'drf_spectacular',

    # Django CORS headers package that handles Cross-Origin
    # Resource Sharing (CORS)
    # headers, allowing frontend applications from different
    # domains to access the API.
    'corsheaders',

    # ASGI WebSocket support for Lens execution Nodes.
    'channels',

    # A Django app that provides support for periodic task scheduling
    # using Celery. It allows you to manage and schedule tasks in a
    # database-backed way, making it easier to handle recurring tasks.
    'django_celery_beat',

    # A Django app that stores the results of Celery tasks in the database,
    # allowing for easy retrieval and management of task outcomes.
    'django_celery_results',

]

# Project-Specific Apps
INSTALLED_APPS += [
    'core',
    'accounts',
    'lens',
    'agentcore_metering.adapters.django',
    'agentcore_task.adapters.django',
    'agentcore_notifier.adapters.django',
]

# The ID of the site that this Django project is associated with.
# This is required for django.contrib.sites and django-allauth
# to work correctly.
SITE_ID = 1

ASGI_APPLICATION = 'core.asgi.application'
_channel_redis_url = os.getenv(
    'CHANNEL_LAYER_REDIS_URL',
    os.getenv('REDIS_URL', 'redis://redis:6379/2'),
)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'core.channel_layers.RedisChannelLayer',
        'CONFIG': {
            'brpop_timeout': float(
                os.getenv('CHANNEL_LAYER_BRPOP_TIMEOUT', '1')
            ),
            'hosts': [_channel_redis_url],
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # CORS middleware should be placed as high as possible in the
    # middleware stack, especially before any middleware that can
    # generate responses such as CommonMiddleware or WhiteNoiseMiddleware.
    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Middleware for django-allauth that manages account-related operations,
    # such as handling user sessions and account state.
    "allauth.account.middleware.AccountMiddleware",

    # Custom middleware to map browser language codes to Django
    # language codes. Must be placed before LocaleMiddleware
    'core.middleware.LanguageCodeMappingMiddleware',

    # 'django.middleware.locale.LocaleMiddleware' is Django's
    # localization middleware. It sets the language environment
    # based on the user's language preferences. The middleware
    # checks headers (e.g., Accept-Language) or session settings.
    'django.middleware.locale.LocaleMiddleware',
]

MIDDLEWARE += [
    # Custom middleware
]

ROOT_URLCONF = 'core.urls'
TEST_RUNNER = 'core.test_runner.ProjectDiscoverRunner'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR.parent, 'accounts', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.frontend_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# ============================
# Database Configuration
# ============================
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Database related settings moved to database.py

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]

# ============================
# Internationalization Configuration
# https://docs.djangoproject.com/en/5.1/topics/i18n/
# ============================

# LANGUAGE_CODE: Specifies the default language code for the application.
# This determines the language strings used by Django. For example, setting
# it to 'en-us' will make Django use American English translations. To
# support other languages, change it to the appropriate language code,
# such as 'zh-hans' for Simplified Chinese.
LANGUAGE_CODE = 'en'

# LANGUAGES: Defines a list of supported languages for the project. It is
# structured as tuples, where the first element is the language code (e.g.,
# 'en-us' for American English, 'de' for German), and the second is the
# language's display name. The display names are usually wrapped in the
# gettext translation function _() for internationalization support. These
# languages appear in Django's language switcher for multi-language support.
# Example: ('zh-hans', _('Simplified Chinese')) adds support
# for Simplified Chinese.
LANGUAGES = (
    ('zh-hans', '简体中文'),
    ('en', 'English'),
    ('es', 'Español'),
)

# TIME_ZONE: Default time zone for dates/times. Set to UTC so that values
# read from the DB (stored in UTC) are not converted when accessed in code.
# API and admin then expose UTC; frontend handles user timezone conversion.
TIME_ZONE = 'UTC'

# USE_I18N: Enables internationalization support. When set to True, Django
# loads translation files and handles language-specific functionalities. Set
# this to False if the application does not require multi-language support.
USE_I18N = True

# USE_L10N: Enables localization support. When set to True, Django adjusts
# the format of dates, times, and numbers based on the language code and
# time zone. For example, date formats may change from 'YYYY-MM-DD' to
# 'DD/MM/YYYY' depending on the language and region.
USE_L10N = True

# USE_TZ: Enables time zone support. When set to True, Django stores dates
# and times in a timezone-aware format. Time is stored in UTC in the database
# and converted to the user's local time zone when displayed. Set to False
# if the application does not require time zone handling.
USE_TZ = True

# LOCALE_PATHS: Specifies the paths for translation files. This global setting
# combines the 'locale' directory with the project's root directory (BASE_DIR),
# so all translation files are stored in the 'locale' folder at the project
# root.
#
# You can also set translation file paths for individual apps. Each app can
# have its own 'locale' directory for storing translation files. For example,
# the translations for the 'accounts' app can be stored in:
# 'accounts/locale/zh_hans/LC_MESSAGES'.
LOCALE_PATHS = [
    os.path.join(BASE_DIR.parent, 'locale'),
]

# Language code mapping from browser Accept-Language to Django language
# codes. This allows browsers sending various language code formats to be
# mapped to Django's standardized language codes. The mapping is used by
# LanguageCodeMappingMiddleware.
#
# Common browser language codes -> Django language codes:
# - Chinese variants: zh-CN, zh -> zh-hans
# - English variants: en-US, en-GB, en-AU, etc. -> en (handled by Django)
# - Spanish variants: es-ES, es-MX, es-AR, etc. -> es
# - Other languages: mapped to default 'en' if not supported
LANGUAGE_CODE_MAPPING = {
    # Chinese variants
    'zh-cn': 'zh-hans',
    'zh': 'zh-hans',
    # Traditional Chinese -> Simplified (fallback)
    'zh-tw': 'zh-hans',
    # Hong Kong Chinese -> Simplified (fallback)
    'zh-hk': 'zh-hans',
    # Singapore Chinese -> Simplified
    'zh-sg': 'zh-hans',
    # Macau Chinese -> Simplified (fallback)
    'zh-mo': 'zh-hans',

    # English variants (Django's LocaleMiddleware handles these
    # automatically via language prefix matching, but included here
    # for completeness and explicit control)
    # US English
    'en-us': 'en',
    # UK English
    'en-gb': 'en',
    # Australia English
    'en-au': 'en',
    # Canada English
    'en-ca': 'en',
    # New Zealand English
    'en-nz': 'en',
    # Ireland English
    'en-ie': 'en',
    # South Africa English
    'en-za': 'en',

    # Spanish variants
    'es': 'es',
    'es-es': 'es',
    'es-mx': 'es',
    'es-ar': 'es',
    'es-cl': 'es',
    'es-co': 'es',
    'es-pe': 'es',
}

# ============================
# Static and Media Files
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# ============================

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = 'static/'

# User-uploaded media (e.g. Lens question image attachments). The
# storage volume is mounted into both the API and worker containers so
# uploads (API) and vision preprocessing (worker) share the same path.
MEDIA_URL = 'media/'
MEDIA_ROOT = os.environ.get("LENS_MEDIA_ROOT", "/opt/storage/media")
DOCUMENT_ATTACHMENT_TTL_SECONDS = int(
    os.getenv("DOCUMENT_ATTACHMENT_TTL_SECONDS", "86400")
)
DOCUMENT_ATTACHMENT_STORAGE_ROOT = "/opt/document-attachments"

# Deliverable files generated by a LensNode run (e.g. an HTML brief) and
# delivered to the user for download. Kept in a dedicated, named storage
# backend on its own volume so it can later be swapped to object storage
# (django-storages S3/OSS) by changing only the "deliverables" entry —
# `.url()` then returns a presigned URL. The bytes are uploaded to the
# control plane at produce time; the control plane never reads the node's
# volume. See issue #14.
DELIVERABLE_STORAGE_ROOT = os.getenv(
    "DELIVERABLE_STORAGE_ROOT", "/opt/deliverables"
)

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
    "deliverables": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {"location": DELIVERABLE_STORAGE_ROOT},
    },
    "document_attachments": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {"location": DOCUMENT_ATTACHMENT_STORAGE_ROOT},
    },
}

# Hard ceiling on a single uploaded deliverable. The upload path is a
# node-to-control-plane POST that does not pass through nginx, so it has
# no client_max_body_size backstop; this bounds one file to keep a buggy
# or compromised node from filling the deliverables volume.
DELIVERABLE_MAX_BYTES = int(
    os.getenv("DELIVERABLE_MAX_BYTES", str(50 * 1024 * 1024))
)

# ============================
# File Upload Configuration
# ============================

# Maximum size for uploaded files (in bytes)
# 100MB = 100 * 1024 * 1024 bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB

# Maximum size for request data (in bytes)
# This includes all POST data, not just file uploads
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB

# Maximum number of fields in a form
FILE_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Maximum number of files that can be uploaded in a single request
FILE_UPLOAD_MAX_NUMBER_FILES = 100

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================
# Logging Configuration
# ============================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "INFO",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
    },
}

# ============================
# URL Configuration
# ============================
# APPEND_SLASH: Controls Django's URL trailing slash behavior.
# When set to False, Django will not automatically append a
# trailing slash to URLs that lack one.
#
# By default (True), if a URL doesn't match any pattern and
# doesn't end in a slash,
# Django redirects to the same URL with a slash appended. For example:
# - Request to 'example.com/path' redirects to 'example.com/path/'
#
# When False:
# - No automatic redirection occurs
# - URLs must match patterns exactly as defined in urls.py
# - Useful for REST APIs where trailing slashes may not be desired
# - Helps maintain cleaner URLs without redirects
APPEND_SLASH = False


# ============================
# CORS Configuration
# ============================

# Allow all origins configuration from environment variable
# Set to 'true' for development convenience, 'false' for production security
CORS_ALLOW_ALL_ORIGINS = (
    os.getenv('CORS_ALLOW_ALL_ORIGINS', 'false').lower() == "true"
)

# Specific allowed origins from environment variable
# Only used when CORS_ALLOW_ALL_ORIGINS is False
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000'
).split(",")

# Allow credentials to be included in CORS requests
CORS_ALLOW_CREDENTIALS = True

# Headers that can be used during the actual request
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Methods that can be used during the actual request
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ============================
# Session and Cookie Configuration
# ============================

# Session cookie configuration
# SameSite='Lax' is secure for most cases and prevents CSRF attacks
# while still allowing top-level navigation cookies
SESSION_COOKIE_SAMESITE = 'Lax'

# Secure=True requires HTTPS; set False for local development
# In production, this should be True
SESSION_COOKIE_SECURE = os.getenv('DJANGO_DEBUG', 'false').lower() != "true"

# Allow session cookies to be shared across subdomains (if needed)
# SESSION_COOKIE_DOMAIN = os.getenv('SESSION_COOKIE_DOMAIN', None)

# CSRF cookie configuration
# SameSite='Lax' allows cookies during top-level navigation
# (like Stripe payment redirects) while providing CSRF protection
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = os.getenv('DJANGO_DEBUG', 'false').lower() != "true"
CSRF_COOKIE_HTTPONLY = False

# ============================
# External Libraries Configuration
# ============================
from .celery import *
from .rest import *
from .swagger import *
from .cache import *
STORAGE_ROOT = os.getenv("STORAGE_ROOT", "/opt/storage")

# ============================
# DRF Spectacular Configuration
# ============================

# DRF Spectacular settings for API documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'SourceLens API',
    'DESCRIPTION': 'API documentation for SourceLens project',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'CONTACT': {
        'name': 'Ray Sun',
        'email': 'xiaoquqi@gmail.com',
    },
    'LICENSE': {
        'name': 'MIT License',
    },
    'TAGS': [
        {'name': 'auth', 'description': 'Authentication endpoints'},
        {'name': 'config', 'description': 'Global configuration endpoints'},
        {
            'name': 'task-management',
            'description': 'Unified task management endpoints',
        },
        {
            'name': 'llm-tracking',
            'description': 'LLM usage tracking and config (admin API)',
        },
    ],
}
