# Generated by Django 5.1.4 on 2026-09-21 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lens", "0059_lensnode_health_probe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executionsnapshot",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="execution_snapshots",
                to="lens.connection",
            ),
        ),
        migrations.AlterField(
            model_name="plugininvocation",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plugin_invocations",
                to="lens.connection",
            ),
        ),
    ]
