# Generated by Django 5.1.4 on 2026-09-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0062_session_legacy_insert_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantpluginbinding',
            name='decision_gates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
