# Generated by Django 5.1.4 on 2026-09-24 09:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lens", "0063_assistantpluginbinding_decision_gates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("enabled", models.BooleanField(db_default=True, default=True)),
                ("events", models.JSONField(blank=True, db_default=[], default=list)),
                ("token_threshold", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rounds_threshold",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("channel_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "email_recipients",
                    models.JSONField(blank=True, db_default=[], default=list),
                ),
                (
                    "assistants",
                    models.ManyToManyField(
                        blank=True, related_name="alert_rules", to="lens.assistant"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lens_alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("run_failed", "Run failed"),
                            ("token_exceeded", "Token exceeded"),
                            ("rounds_exceeded", "Rounds exceeded"),
                        ],
                        max_length=32,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dispatched", "Dispatched"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="dispatched",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_events",
                        to="lens.run",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_events",
                        to="lens.alertrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="lens_alertevent_type_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rule", "run", "event_type"),
                        name="lens_alertevent_rule_run_type_uniq",
                    )
                ],
            },
        ),
    ]
