# Generated by Django 5.1.4 on 2026-09-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0063_assistantpluginbinding_decision_gates'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantpluginbinding',
            name='decision_auto',
            field=models.BooleanField(default=True),
        ),
    ]
