from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import (
    AdminGroupAccessDetailView,
    AdminRunCancelView,
    AdminRunDetailView,
    AdminRunDiagnosticsView,
    AdminRunDiagnosticTurnsView,
    AdminRunListView,
    AdminRunResumeView,
    AdminRunRetryView,
    AdminRunTrajectoryView,
    AdminSharedQAViewSet,
    AdminUserAccessDetailView,
    AssistantViewSet,
    ConnectionViewSet,
    DataSourceCredentialViewSet,
    DataSourceViewSet,
    EnvironmentVariableSetViewSet,
    GlobalSettingViewSet,
    LensAttachmentView,
    LensNodeAIGatewayView,
    LensNodeDelegationView,
    LensNodeDeliverableUploadView,
    LensNodeHistoryArtifactView,
    LensNodeRunAttachmentView,
    LensNodeSkillPackageView,
    LensNodeViewSet,
    MCPServerViewSet,
    PluginRegistryViewSet,
    PluginCredentialLeaseView,
    PluginCredentialMaterialView,
    PluginExecutionSnapshotView,
    PluginInvocationViewSet,
    PluginToolExecutionSnapshotView,
    PluginRPCView,
    PublicAssistantView,
    PublicSharedQAFileView,
    PublicSharedQAListView,
    PublicSharedQAPdfView,
    PublicSharedQAView,
    RunCitationSourceView,
    RunOutputFileDownloadView,
    RunViewSet,
    SessionViewSet,
    SharedQAViewSet,
    SkillViewSet,
    admin_run_trajectory_stream_view,
    run_stream_view,
)

router = DefaultRouter()
router.register("assistants", AssistantViewSet, basename="lens-assistants")
router.register("sessions", SessionViewSet, basename="lens-sessions")
router.register("runs", RunViewSet, basename="lens-runs")
router.register("shares", SharedQAViewSet, basename="lens-shares")
router.register(
    "admin/shares",
    AdminSharedQAViewSet,
    basename="lens-admin-shares",
)
router.register(
    "admin/lensnodes", LensNodeViewSet, basename="lens-admin-lensnodes"
)
router.register(
    "admin/datasources",
    DataSourceViewSet,
    basename="lens-admin-datasources",
)
router.register(
    "admin/credentials",
    DataSourceCredentialViewSet,
    basename="lens-admin-credentials",
)
router.register(
    "admin/plugins",
    PluginRegistryViewSet,
    basename="lens-admin-plugins",
)
router.register(
    "admin/connections",
    ConnectionViewSet,
    basename="lens-admin-connections",
)
router.register(
    "admin/plugin-invocations",
    PluginInvocationViewSet,
    basename="lens-admin-plugin-invocations",
)
router.register(
    "admin/environment-variable-sets",
    EnvironmentVariableSetViewSet,
    basename="lens-admin-environment-variable-sets",
)
router.register("admin/skills", SkillViewSet, basename="lens-admin-skills")
router.register(
    "admin/mcp-servers",
    MCPServerViewSet,
    basename="lens-admin-mcp-servers",
)
router.register(
    "admin/global-settings",
    GlobalSettingViewSet,
    basename="lens-admin-global-settings",
)

urlpatterns = [
    path("plugin-runtime/<str:plugin_key>/rpc/", PluginRPCView.as_view()),
    path(
        "plugin-runtime/tool-snapshots/",
        PluginToolExecutionSnapshotView.as_view(),
        name="lens-plugin-tool-execution-snapshot",
    ),
    path(
        "plugin-runtime/leases/",
        PluginCredentialLeaseView.as_view(),
        name="lens-plugin-credential-lease",
    ),
    path(
        "plugin-runtime/leases/<uuid:lease_uuid>/material/",
        PluginCredentialMaterialView.as_view(),
        name="lens-plugin-credential-material",
    ),
    path(
        "plugin-runtime/snapshots/<uuid:snapshot_uuid>/",
        PluginExecutionSnapshotView.as_view(),
        name="lens-plugin-execution-snapshot",
    ),
    path(
        "admin/access/users/<int:user_id>/",
        AdminUserAccessDetailView.as_view(),
        name="lens-admin-user-access-detail",
    ),
    path(
        "admin/access/groups/<int:group_id>/",
        AdminGroupAccessDetailView.as_view(),
        name="lens-admin-group-access-detail",
    ),
    path(
        "public/assistants/<slug:slug>/",
        PublicAssistantView.as_view(),
        name="lens-public-assistant",
    ),
    path(
        "public/assistants/<slug:slug>/qa/",
        PublicSharedQAListView.as_view(),
        name="lens-public-assistant-qa",
    ),
    path(
        "public/qa/<str:token>/",
        PublicSharedQAView.as_view(),
        name="lens-public-qa",
    ),
    path(
        "public/qa/<str:token>/pdf/",
        PublicSharedQAPdfView.as_view(),
        name="lens-public-qa-pdf",
    ),
    path(
        "public/qa/<str:token>/files/<uuid:uuid>/",
        PublicSharedQAFileView.as_view(),
        name="lens-public-qa-file",
    ),
    path(
        "runs/<uuid:uuid>/stream/",
        run_stream_view,
        name="lens-run-stream",
    ),
    path(
        "runs/<uuid:run_uuid>/citations/<str:citation_id>/",
        RunCitationSourceView.as_view(),
        name="lens-run-citation-source",
    ),
    path(
        "admin/runs/",
        AdminRunListView.as_view(),
        name="lens-admin-runs",
    ),
    path(
        "admin/runs/<uuid:uuid>/",
        AdminRunDetailView.as_view(),
        name="lens-admin-run-detail",
    ),
    path(
        "admin/runs/<uuid:uuid>/cancel/",
        AdminRunCancelView.as_view(),
        name="lens-admin-run-cancel",
    ),
    path(
        "admin/runs/<uuid:uuid>/retry/",
        AdminRunRetryView.as_view(),
        name="lens-admin-run-retry",
    ),
    path(
        "admin/runs/<uuid:uuid>/resume/",
        AdminRunResumeView.as_view(),
        name="lens-admin-run-resume",
    ),
    path(
        "admin/runs/<uuid:run_uuid>/trajectory/",
        AdminRunTrajectoryView.as_view(),
        name="lens-admin-run-trajectory",
    ),
    path(
        "admin/runs/<uuid:run_uuid>/trajectory/stream/",
        admin_run_trajectory_stream_view,
        name="lens-admin-run-trajectory-stream",
    ),
    path(
        "admin/runs/<uuid:run_uuid>/diagnostics/",
        AdminRunDiagnosticsView.as_view(),
        name="lens-admin-run-diagnostics",
    ),
    path(
        (
            "admin/runs/<uuid:run_uuid>/diagnostics/"
            "<uuid:diagnostic_uuid>/turns/"
        ),
        AdminRunDiagnosticTurnsView.as_view(),
        name="lens-admin-run-diagnostic-turns",
    ),
    path(
        "admin/global-settings/system-health/",
        GlobalSettingViewSet.as_view(
            {
                "get": "system_health",
                "patch": "system_health",
            }
        ),
        name="lens-admin-global-settings-system-health",
    ),
    path(
        "admin/global-settings/<str:key>/",
        GlobalSettingViewSet.as_view(
            {
                "get": "retrieve",
                "patch": "partial_update",
                "put": "update",
                "delete": "destroy",
            }
        ),
        name="lens-admin-global-settings-detail",
    ),
    path(
        "attachments/<uuid:uuid>/",
        LensAttachmentView.as_view(),
        name="lens-attachment",
    ),
    path(
        "output-files/<uuid:uuid>/",
        RunOutputFileDownloadView.as_view(),
        name="lens-output-file",
    ),
    *router.urls,
    path(
        "lensnode/ai-gateway/",
        LensNodeAIGatewayView.as_view(),
        name="lens-lensnode-ai-gateway",
    ),
    path(
        "lensnode/runs/<uuid:run_uuid>/delegations/",
        LensNodeDelegationView.as_view(),
        name="lens-lensnode-delegations",
    ),
    path(
        (
            "lensnode/runs/<uuid:run_uuid>/delegations/"
            "<uuid:child_uuid>/"
        ),
        LensNodeDelegationView.as_view(),
        name="lens-lensnode-delegation-detail",
    ),
    path(
        "lensnode/skills/<uuid:uuid>/package/",
        LensNodeSkillPackageView.as_view(),
        name="lens-lensnode-skill-package",
    ),
    path(
        "lensnode/runs/<uuid:run_uuid>/attachments/<uuid:uuid>/",
        LensNodeRunAttachmentView.as_view(),
        name="lens-lensnode-run-attachment",
    ),
    path(
        "lensnode/runs/<uuid:run_uuid>/history-artifacts/<uuid:uuid>/",
        LensNodeHistoryArtifactView.as_view(),
        name="lens-lensnode-history-artifact",
    ),
    path(
        "lensnode/deliverables/",
        LensNodeDeliverableUploadView.as_view(),
        name="lens-lensnode-deliverable-upload",
    ),
]
